# Generated by Django 3.2.14 on 2022-07-17 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review',
        ),
    ]
