# Generated by Django 3.2.14 on 2022-07-20 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
