# Generated by Django 3.2.14 on 2022-07-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0005_auto_20220717_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='location',
            field=models.CharField(default='Dublin', max_length=80),
        ),
    ]
