# Generated by Django 3.2.14 on 2022-07-20 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0005_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='active',
            new_name='approved',
        ),
    ]
