# Generated by Django 3.2.14 on 2022-07-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0006_comment_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='location',
            field=models.CharField(default='e.g Dublin', max_length=80),
        ),
    ]
