# Generated by Django 3.2.14 on 2022-07-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0007_comment_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 *'), (2, '2 *'), (3, '3 *'), (4, '4 *'), (5, '5 *')], default='5'),
        ),
    ]
