# Generated by Django 3.2.14 on 2022-07-19 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0007_alter_comment_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
