# Generated by Django 3.2.14 on 2022-07-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0009_userprofile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default='5 stars'),
        ),
    ]
