# Generated by Django 3.2.14 on 2022-07-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0010_auto_20220724_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
