# Generated by Django 3.2.14 on 2022-07-24 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0011_userprofile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
    ]
